# Change these first
owner: Cotterville # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: DMRTexas.net
    url: https://dmrtexas.net/doku.php?id=start
    maxResponseTime: 5000
    icon: https://raw.githubusercontent.com/Cotterville/upptime/master/assets/texas-favicon.ico
  - name: CBridge - CBridge 2.0
    url: 64.111.99.38
    check: "tcp-ping"
    port: 42420
    maxResponseTime: 5000
    icon: https://raw.githubusercontent.com/Cotterville/upptime/master/assets/tower-favicon.ico
  - name: CBridge - Chicagoland
    url: 107.191.49.134
    check: "tcp-ping"
    port: 42420
    maxResponseTime: 5000
    icon: https://raw.githubusercontent.com/Cotterville/upptime/master/assets/tower-favicon.ico
  - name: CBridge - DilloDMR
    url: 45.55.152.18
    check: "tcp-ping"
    port: 42420
    maxResponseTime: 5000
    icon: https://raw.githubusercontent.com/Cotterville/upptime/master/assets/tower-favicon.ico
  - name: CBridge - K4USD
    url: 160.94.103.68
    check: "tcp-ping"
    port: 42420
    maxResponseTime: 5000
    icon: https://raw.githubusercontent.com/Cotterville/upptime/master/assets/tower-favicon.ico
  - name: CBridge - Lonestar DMR
    url: 192.92.239.155
    check: "tcp-ping"
    port: 42420
    maxResponseTime: 5000
    icon: https://raw.githubusercontent.com/Cotterville/upptime/master/assets/tower-favicon.ico
  - name: CBridge - SE Texas
    url: 199.66.149.2
    check: "tcp-ping"
    port: 443
    maxResponseTime: 5000
    icon: https://raw.githubusercontent.com/Cotterville/upptime/master/assets/tower-favicon.ico
  - name: CBridge - TXGulfCoast
    url: 66.170.192.14
    check: "tcp-ping"
    port: 42420
    maxResponseTime: 5000
    icon: https://raw.githubusercontent.com/Cotterville/upptime/master/assets/tower-favicon.ico
  - name: CBridge - TxMARC
    url: 72.20.134.101
    check: "tcp-ping"
    port: 42420
    maxResponseTime: 5000
    icon: https://raw.githubusercontent.com/Cotterville/upptime/master/assets/tower-favicon.ico
  - name: Brandmeister 3102 (Dallas)
    url: 74.91.114.19
    check: "tcp-ping"
    maxResponseTime: 5000
    icon: https://raw.githubusercontent.com/Cotterville/upptime/master/assets/server-favicon.ico
  - name: Brandmeister 3103 (San Jose)
    url: 74.91.118.251
    check: "tcp-ping"
    maxResponseTime: 5000
    icon: https://raw.githubusercontent.com/Cotterville/upptime/master/assets/server-favicon.ico
  - name: Brandmeister 3104 (Chicago)
    url: 162.248.88.117
    check: "tcp-ping"
    maxResponseTime: 5000
    icon: https://raw.githubusercontent.com/Cotterville/upptime/master/assets/server-favicon.ico

status-website:
  cname: status.dmrtexas.net
  logoUrl: https://raw.githubusercontent.com/Cotterville/upptime/9918dc13320c37d1eaa1d8f4718ef772e68fcc05/assets/DMRTexasLogo.png
  name: "Status@DMRTexas"
  introTitle: "Welcome to the status page for **DMRTexas**"
  introMessage: "See the uptime status of the CBridges and BM servers commonly used with DMR in Texas."
  status-website:
  theme: dark
  navbar:
    - title: Home
      href: https://dmrtexas.net/
    - title: Status
      href: /

# Updated on June 12, 2024
# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
