# Change these first
owner: Cotterville # Your GitHub organization or username, where this repository lives
repo: upptime # The name of this repository

sites:
  - name: DMRTexas.net
    url: https://dmrtexas.net
    check: "tcp-ping"
    port: 443
  - name: Brandmeister 3102
    url: 74.91.114.19
    check: "tcp-ping"
    port: 80
  - name: Brandmeister 3103
    url: 74.91.118.251
    check: "tcp-ping"
    port: 80
  - name: Brandmeister 3104
    url: 162.248.88.117
    check: "tcp-ping"
    port: 80
  - name: CBridge - CBridge 2.0
    url: 64.111.99.38
    check: "tcp-ping"
    port: 42420
  - name: CBridge - Chicagoland
    url: 107.191.49.134
    check: "tcp-ping"
    port: 42420
  - name: CBridge - DilloDMR
    url: 45.55.152.18
    check: "tcp-ping"
    port: 42420
  - name: CBridge - K4USD
    url: 160.94.103.68
    check: "tcp-ping"
    port: 42420
  - name: CBridge - Lonestar DMR
    url: 192.92.239.155
    check: "tcp-ping"
    port: 42420
  - name: CBridge - SE Texas
    url: https://cbridge.crhrc.org
    check: "tcp-ping"
    port: 443
  - name: CBridge - TXGulfCoast
    url: 70.234.211.235
    check: "tcp-ping"
    port: 42420
  - name: CBridge - TxMARC
    url: cbridge.txmarc.net
    check: "tcp-ping"
    port: 42420

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  cname: status.dmrtexas.net
  # baseUrl: /your-repo-name
  logoUrl: https://raw.githubusercontent.com/Cotterville/upptime/9918dc13320c37d1eaa1d8f4718ef772e68fcc05/assets/DMRTexasLogo.png
  # name: DMRTexas
  introTitle: "This is the status page for **DMRTexas**"
  introMessage: "This page will show you the status of the CBridges and BM servers commonly used with DMR in Texas."
  navbar:
    - title: Home
      href: https://dmrtexas.net/
    - title: Status
      href: /
  status-website:
  theme: dark

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
